# Generated by Django 5.2.8 on 2025-11-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_url', models.CharField(max_length=500)),
                ('data_captura', models.DateTimeField(auto_now_add=True)),
                ('nivel_audio_db', models.FloatField(default=0, help_text='Energia do som (0-255)')),
                ('variacao_magnetica', models.FloatField(default=0, help_text='Delta da Bússola')),
                ('score_coincidencia', models.IntegerField(default=1)),
            ],
        ),
    ]
