# Generated by Django 5.2.8 on 2025-11-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='nivel_audio_db',
            field=models.FloatField(default=0, help_text='Volume do som no momento'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='variacao_magnetica',
            field=models.FloatField(default=0, help_text='Variação da Bússola'),
        ),
    ]
