# Generated by Django 5.2.10 on 2026-02-25 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evidencia_nivel_audio_db_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoEVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sessão EVP', max_length=200)),
                ('status', models.CharField(choices=[('ativa', 'Em Andamento'), ('encerrada', 'Encerrada')], default='ativa', max_length=15)),
                ('local', models.CharField(blank=True, max_length=300)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('total_capturas', models.IntegerField(default=0)),
                ('total_anomalias', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sessão EVP',
                'verbose_name_plural': 'Sessões EVP',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SessaoInvestigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Investigação sem título', max_length=200)),
                ('local', models.CharField(blank=True, max_length=300, verbose_name='Local da Investigação')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Em Andamento'), ('encerrada', 'Encerrada'), ('analisando', 'Em Análise IA')], default='ativa', max_length=15)),
                ('notas', models.TextField(blank=True, verbose_name='Notas do Investigador')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('total_anomalias', models.IntegerField(default=0)),
                ('score_maximo', models.IntegerField(default=0)),
                ('energia_media', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Sessão de Investigação',
                'verbose_name_plural': 'Sessões de Investigação',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'ordering': ['-data_captura'], 'verbose_name': 'Evidência', 'verbose_name_plural': 'Evidências'},
        ),
        migrations.AddField(
            model_name='evidencia',
            name='analise_ia',
            field=models.TextField(blank=True, verbose_name='Análise da IA'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='ia_classificacao',
            field=models.CharField(blank=True, help_text='O que a IA acha que é', max_length=30, verbose_name='Classificação IA'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='ia_confianca',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiança IA (%)'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='origem_disparo',
            field=models.CharField(default='desconhecido', max_length=50),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='temperatura',
            field=models.FloatField(blank=True, help_text='Temperatura ambiente (°C)', null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tipo',
            field=models.CharField(choices=[('visual', 'Anomalia Visual (Face/Forma)'), ('sonora', 'Anomalia Sonora (Audio Spike)'), ('magnetica', 'Anomalia Magnética (Bússola)'), ('multipla', 'Anomalia Múltipla (Multi-Sensor)'), ('manual', 'Captura Manual')], default='visual', max_length=15),
        ),
        migrations.CreateModel(
            name='RegistroEVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_captura', models.DateTimeField(auto_now_add=True)),
                ('transcricao', models.TextField(blank=True, verbose_name='Transcrição (Speech API)')),
                ('nivel_audio', models.FloatField(default=0, verbose_name='Nível de Áudio (RMS)')),
                ('frequencia_dominante', models.FloatField(blank=True, null=True, verbose_name='Frequência Dominante (Hz)')),
                ('frequencias_anomalas', models.JSONField(default=list, verbose_name='Frequências Anômalas (Hz)')),
                ('variacao_magnetica', models.FloatField(default=0)),
                ('e_anomalia', models.BooleanField(default=False, verbose_name='É Anomalia?')),
                ('classificacao_ia', models.CharField(choices=[('silencio', 'Silêncio'), ('ruido', 'Ruído Ambiental'), ('voz_humana', 'Voz Humana Normal'), ('padrao_anomalo', 'Padrão Anômalo'), ('possivel_evp', 'Possível EVP'), ('evp_confirmado', 'EVP Confirmado pela IA')], default='silencio', max_length=20, verbose_name='Classificação IA')),
                ('analise_ia', models.TextField(blank=True, verbose_name='Análise Detalhada IA')),
                ('confianca_ia', models.FloatField(blank=True, null=True, verbose_name='Confiança IA (%)')),
                ('nota_paranormal', models.IntegerField(default=0, verbose_name='Nota Paranormal (0-10)')),
                ('mensagem_detectada', models.TextField(blank=True, verbose_name='Mensagem Detectada pela IA')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.sessaoevp', verbose_name='Sessão EVP')),
            ],
            options={
                'verbose_name': 'Registro EVP',
                'verbose_name_plural': 'Registros EVP',
                'ordering': ['-data_captura'],
            },
        ),
        migrations.AddField(
            model_name='sessaoevp',
            name='sessao_investigacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_evp', to='core.sessaoinvestigacao', verbose_name='Sessão de Investigação'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='sessao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.sessaoinvestigacao', verbose_name='Sessão'),
        ),
    ]
