# Generated by Django 5.2.10 on 2026-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sessaoevp_sessaoinvestigacao_alter_evidencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='dimensao_estimada',
            field=models.CharField(default='3D', max_length=20, verbose_name='Dimensão Estimada'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='fusao_dados',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados de Fusão Aura Core'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='ia_classificacao',
            field=models.CharField(blank=True, help_text='O que a IA acha que é', max_length=100, verbose_name='Classificação IA'),
        ),
    ]
