# Generated by Django 5.2.10 on 2026-02-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evidencia_dimensao_estimada_evidencia_fusao_dados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroevp',
            name='dimensao_estimada',
            field=models.CharField(default='3D', max_length=20, verbose_name='Dimensão Estimada'),
        ),
        migrations.AddField(
            model_name='registroevp',
            name='fusao_dados',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados de Fusão Aura Core'),
        ),
    ]
