# Generated by Django 5.2.10 on 2026-02-25 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registroevp_dimensao_estimada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSintese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sessao', models.DateTimeField(default=django.utils.timezone.now)),
                ('entidade_nome', models.CharField(default='Desconhecida', max_length=200)),
                ('densidade_final', models.CharField(default='3D', max_length=50)),
                ('coerencia_maxima', models.FloatField(default=0)),
                ('log_dialogo', models.JSONField(default=list)),
                ('semente_principal', models.TextField(blank=True)),
                ('snapshot_url', models.CharField(blank=True, max_length=500, null=True)),
                ('sessao_investigacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinteses', to='core.sessaoinvestigacao')),
            ],
            options={
                'verbose_name': 'Registro de Síntese',
                'verbose_name_plural': 'Registros de Síntese',
                'ordering': ['-data_sessao'],
            },
        ),
    ]
