# Generated by Django 5.2.10 on 2026-02-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registrosintese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='dimensao_estimada',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='fusao_dados',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='amplitude_db',
            field=models.FloatField(default=0, verbose_name='Amplitude (dB)'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='frequencia_hz',
            field=models.FloatField(default=0, verbose_name='Frequência (Hz)'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='kp_index_captura',
            field=models.FloatField(default=0, verbose_name='Índice Kp (NOAA)'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='luminosidade_lux',
            field=models.FloatField(blank=True, null=True, verbose_name='Luz (Lux)'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='snr_ratio',
            field=models.FloatField(default=0, verbose_name='SNR (Signal-to-Noise)'),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='afinidade_fluidica',
            field=models.FloatField(default=0, verbose_name='Afinidade (%)'),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='classe_espirito',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Classe (Kardec)'),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='frequencia_base_hz',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='kp_index_medio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='snr_medio',
            field=models.FloatField(default=0),
        ),
    ]
