# Generated by Django 5.2.10 on 2026-02-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_evidencia_dimensao_estimada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='obs_bpm',
            field=models.FloatField(default=0, verbose_name='BPM do Observador'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='obs_stress',
            field=models.FloatField(default=0, verbose_name='Estresse (%)'),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='coerencia_cardiaca_media',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='metabolic_drain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='obs_bpm_medio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registrosintese',
            name='obs_stress_medio',
            field=models.FloatField(default=0),
        ),
    ]
